# Data preprocessing
Chenyang Wu

In [1]:
import pandas as pd

## read data and check

In [2]:
nflx = pd.read_csv('NFLX.csv')
print(nflx.head())

         Date      Open      High       Low     Close  Adj Close     Volume
0  2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1  2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2  2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3  2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4  2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200

In [3]:
# transform the date column to datetime format
nflx['Date'] = pd.to_datetime(nflx['Date'])
nflx = nflx.set_index('Date')
print(nflx.head())

                Open      High       Low     Close  Adj Close     Volume
Date
2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200

## get yearly netflix price(use adj close to get average)

In [4]:
# yearly average closing price
nflx_yearly = nflx['Adj Close'].resample('YE').mean().to_frame(name='NFLX_AdjClose_mean')

#extract the year from the index and add it as a column
nflx_yearly['Year'] = nflx_yearly.index.year

# reset the index to make 'Year' a column
nflx_yearly = nflx_yearly.reset_index(drop=True)

nflx_yearly.head()

   NFLX_AdjClose_mean  Year
0            0.850172  2002
1            2.081205  2003
2            3.413430  2004
3            2.597262  2005
4            3.690996  2006

In [5]:
nflx_yearly.head()
nflx_yearly.tail()
nflx_yearly.shape

(22, 2)

## Gold price year average

In [7]:
xls = pd.ExcelFile("Gold_price_averages_in_a_range_of_currencies_since_1978.xlsx")
xls.sheet_names

['Disclaimer', 'Yearly_Avg', 'Quarterly_Avg', 'Monthly_Avg']

In [8]:
gold_raw = pd.read_excel(
    "Gold_price_averages_in_a_range_of_currencies_since_1978.xlsx",
    sheet_name="Yearly_Avg",
    header=None
)

gold_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Gold price per troy ounce - Major consumer and...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Source: Bloomberg, Datastream, ICE Benchmark A...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaT,USD,EUR,JPY,GBP,CAD,CHF,INR,...,SAR,IDR,AED,THB,VND,EGP,KRW,RUB,ZAR,AUD
6,NaN,NaN,1978-12-29,193.44,124.7358,NaN,100.65449,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,1979-12-31,304.68,185.06142,67944.1282,143.09014,358.67706,507.32932,NaN,...,1030.00823,191281.9686,1163.93597,6201.36554,NaN,NaN,148048.81715,NaN,256.98018,274.26741
8,NaN,NaN,1980-12-31,614.5,378.19461,138760.0626,263.80259,717.92312,1027.53631,NaN,...,2044.58523,383817.6575,2278.36795,12496.01711,NaN,NaN,366823.49569,NaN,478.27728,538.72535
9,NaN,NaN,1981-12-31,459.26,360.90588,100895.8211,227.01948,550.13388,900.97595,NaN,...,1554.10505,288926.4587,1691.03194,9908.73893,NaN,NaN,315191.83854,NaN,400.43678,399.09781
10,NaN,NaN,1982-12-31,375.3,345.59742,93780.75932,215.53232,462.35812,765.10276,NaN,...,1287.46762,247508.7345,1378.72895,8589.98652,NaN,NaN,276229.04088,NaN,408.52175,371.52085
11,NaN,NaN,1983-12-30,423.66,439.89318,100676.3394,279.24936,521.79192,889.00561,NaN,...,1465.69942,383187.6258,1557.4579,9709.7955,NaN,NaN,331230.2962,NaN,471.3398,469.66252
12,NaN,NaN,1984-12-31,360.78,425.91,85515.02188,269.81553,466.41352,844.60104,NaN,...,1272.30542,369744.3393,1324.72272,8458.99207,NaN,NaN,292467.68745,NaN,527.2089,409.87547
13,NaN,NaN,1985-12-31,317.3,394.08922,75698.58994,246.28501,432.34535,779.09605,NaN,...,1149.83688,351424.4479,1162.19778,8490.61769,NaN,NaN,274967.1316,NaN,703.41633,452.90036
14,NaN,NaN,1986-12-31,367.85,351.34774,61804.00416,251.12483,511.4325,658.66393,NaN,...,1365.98238,478895.8826,1351.92474,9567.75152,NaN,NaN,324124.14932,NaN,839.70641,551.85763

In [9]:
gold_data = gold_raw.iloc[6:, :].copy()

# rename the columns to something more meaningful
gold_data = gold_data.rename(columns={
    2: 'Date',
    3: 'USD'
})

# keep only the date and USD columns
gold_data = gold_data[['Date', 'USD']]
gold_data.head()

         Date     USD
6  1978-12-29  193.44
7  1979-12-31  304.68
8  1980-12-31   614.5
9  1981-12-31  459.26
10 1982-12-31   375.3

### Set Date as the index and aggregate by year

In [10]:
# transform the date column to datetime format adn set it as the index
gold_data['Date'] = pd.to_datetime(gold_data['Date'])
gold_data = gold_data.set_index('Date')

# resample the data to yearly frequency and take the mean of the USD column
gold_yearly = gold_data['USD'].resample('YE').mean().to_frame(name='Gold_USD_mean')

# extract the year from the index and add it as a column
gold_yearly['Year'] = gold_yearly.index.year
gold_yearly = gold_yearly.reset_index(drop=True)
gold_yearly.head()

  Gold_USD_mean  Year
0        193.44  1978
1        304.68  1979
2         614.5  1980
3        459.26  1981
4         375.3  1982

## combine with nflx_yearly

In [11]:
combined = pd.merge(
    gold_yearly[['Year', 'Gold_USD_mean']],
    nflx_yearly[['Year', 'NFLX_AdjClose_mean']],
    on='Year',
    how='inner'
)

combined.head()
combined.to_csv("combined_goldandnflx_yearly.csv", index=False)

## double check part!

In [12]:
nflx.head()
nflx.index

DatetimeIndex(['2002-05-23', '2002-05-24', '2002-05-28', '2002-05-29',
               '2002-05-30', '2002-05-31', '2002-06-03', '2002-06-04',
               '2002-06-05', '2002-06-06',
               ...
               '2023-11-21', '2023-11-22', '2023-11-24', '2023-11-27',
               '2023-11-28', '2023-11-29', '2023-11-30', '2023-12-01',
               '2023-12-04', '2023-12-05'],
              dtype='datetime64[us]', name='Date', length=5422, freq=None)

In [13]:
# 2023 netflix data
nflx_2023 = nflx.loc['2023']
print(nflx_2023.head())
print(nflx_2023.tail())

                  Open        High         Low       Close   Adj Close  \
Date
2023-01-03  298.059998  298.390015  288.700012  294.950012  294.950012
2023-01-04  298.239990  311.140015  295.510010  309.410004  309.410004
2023-01-05  307.000000  314.179993  304.549988  309.700012  309.700012
2023-01-06  311.570007  316.769989  303.690002  315.549988  315.549988
2023-01-09  316.829987  321.700012  313.220001  315.170013  315.170013

             Volume
Date
2023-01-03  6764000
2023-01-04  9345100
2023-01-05  8328400
2023-01-06  8959800
2023-01-09  6766600
                  Open        High         Low       Close   Adj Close  \
Date
2023-11-29  479.000000  480.989990  474.489990  477.190002  477.190002
2023-11-30  475.309998  478.589996  470.420013  473.970001  473.970001
2023-12-01  473.170013  475.230011  464.600006  465.739990  465.739990
2023-12-04  460.989990  461.200012  451.200012  453.899994  453.899994
2023-12-05  450.700012  456.390015  449.579987  455.149994  455.149994

             Volume
Date
2023-11-29  2855500
2023-11-30  4287300
2023-12-01  4338100
2023-12-04  5157700
2023-12-05  3261100

In [14]:
# caculate the mean of the adjusted closing price for 2023
nflx_2023_mean = nflx_2023['Adj Close'].mean()
print(nflx_2023_mean)

383.92948472532186

## Monthly NFLX Prices

In [16]:
# Monthly average adj closing price for Netflix
nflx_monthly = nflx['Adj Close'].resample('ME').mean().to_frame(name='NFLX_AdjClose_m_mean')

# Extract year and month
nflx_monthly['Year'] = nflx_monthly.index.year
nflx_monthly['Month'] = nflx_monthly.index.month

# Reset index
nflx_monthly = nflx_monthly.reset_index(drop=True)

nflx_monthly.head()

   NFLX_AdjClose_m_mean  Year  Month
0              1.135834  2002      5
1              1.038071  2002      6
2              1.110000  2002      7
3              0.870974  2002      8
4              0.828071  2002      9

## Monthly gold prices(Still USD)

In [18]:
# Read monthly gold data from the 'Monthly_Avg' sheet
gold_monthly_raw = pd.read_excel(
    "Gold_price_averages_in_a_range_of_currencies_since_1978.xlsx",
    sheet_name="Monthly_Avg",
    header=None
)

gold_monthly_raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Gold price per troy ounce - Major consumer and...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"Source: Bloomberg, Datastream, ICE Benchmark A...",NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaT,USD,EUR,JPY,GBP,CAD,CHF,INR,...,SAR,IDR,AED,THB,VND,EGP,KRW,RUB,ZAR,AUD
6,NaN,NaN,1978-01-31,207.83,129.2081,NaN,104.62599,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,1978-02-28,227.27,139.53296,44853.10621,113.32103,269.54823,378.77281,NaN,...,754.08837,141796.36585,869.39601,4582.17775,NaN,NaN,111186.57079,NaN,197.00341,198.59663
8,NaN,NaN,1978-03-31,245.67,151.30799,49213.15041,122.54972,293.17263,410.58371,NaN,...,822.3053,153099.5914,939.09373,4949.49689,NaN,NaN,118284.02983,NaN,209.85795,216.65056
9,NaN,NaN,1978-04-28,242.05,149.30073,49989.43254,118.79066,284.20489,407.26165,NaN,...,810.13899,151068.5423,926.22479,4884.52856,NaN,NaN,116507.06192,NaN,204.35324,215.93071
10,NaN,NaN,1978-05-31,239.16,148.76416,51707.16895,115.43299,274.23889,410.50434,NaN,...,817.29641,149744.25491,919.93608,4842.57197,NaN,NaN,115555.93216,NaN,202.76229,215.84825
11,NaN,NaN,1978-06-30,257.62,161.00387,56429.29437,125.1719,297.74976,445.41611,NaN,...,870.65435,160956.98685,983.49532,5208.45227,NaN,NaN,124738.22448,NaN,217.61906,233.02206
12,NaN,NaN,1978-07-31,279.07,173.02949,61069.32085,132.13363,327.40582,474.48575,NaN,...,941.30932,172550.08246,1064.77056,5592.21835,NaN,NaN,132563.71436,NaN,235.56996,251.11908
13,NaN,NaN,1978-08-31,294.74,178.22845,63843.14588,130.47985,342.98376,486.08905,NaN,...,980.38574,182837.92812,1109.8397,5881.49786,NaN,NaN,137305.91238,NaN,248.50654,261.4364
14,NaN,NaN,1978-09-29,300.82,182.02608,65530.16006,134.48051,352.03695,498.52021,NaN,...,1024.75253,190103.61001,1147.1402,6194.89536,NaN,NaN,148383.20219,NaN,251.99387,266.6042

In [20]:
gold_monthly = gold_monthly_raw.iloc[6:, :].copy()

gold_monthly = gold_monthly.rename(columns={
    2: 'Date',
    3: 'USD'
})

gold_monthly = gold_monthly[['Date', 'USD']]
gold_monthly['Date'] = pd.to_datetime(gold_monthly['Date'])
gold_monthly = gold_monthly.set_index('Date')

# Resample to monthly frequency (month-end), take mean
gold_monthly = gold_monthly['USD'].resample('ME').mean().to_frame(name='Gold_USD_m_mean')

gold_monthly['Year'] = gold_monthly.index.year
gold_monthly['Month'] = gold_monthly.index.month
gold_monthly = gold_monthly.reset_index(drop=True)

gold_monthly.head()

  Gold_USD_m_mean  Year  Month
0          207.83  1978      1
1          227.27  1978      2
2          245.67  1978      3
3          242.05  1978      4
4          239.16  1978      5

## Combine monthly gold and nflx

In [21]:
combined_monthly = pd.merge(
    gold_monthly[['Year', 'Month', 'Gold_USD_m_mean']],
    nflx_monthly[['Year', 'Month', 'NFLX_AdjClose_m_mean']],
    on=['Year', 'Month'],
    how='inner'
)

combined_monthly.head()

combined_monthly.to_csv("combined_goldandnflx_monthly.csv", index=False)

## Double check for monthly prices

In [24]:
year = 2023
month = 1

nflx_month_check = nflx.loc[
    (nflx.index.year == year) & (nflx.index.month == month),
    'Adj Close'
]

print("Closing Prices for All Days of the Month:")
print(nflx_month_check)
print("Hand-calculated Monthly Average:", nflx_month_check.mean())

row_month = combined_monthly.loc[
    (combined_monthly['Year'] == year) & (combined_monthly['Month'] == month),
    'NFLX_AdjClose_m_mean'
]

row_value = row_month.iloc[0] 
print("monthly average for 2023-1 within combined_monthly:", row_value)

Closing Prices for All Days of the Month:
Date
2023-01-03    294.950012
2023-01-04    309.410004
2023-01-05    309.700012
2023-01-06    315.549988
2023-01-09    315.170013
2023-01-10    327.540009
2023-01-11    327.260010
2023-01-12    330.130005
2023-01-13    332.820007
2023-01-17    326.220001
2023-01-18    326.329987
2023-01-19    315.779999
2023-01-20    342.500000
2023-01-23    357.420013
2023-01-24    363.829987
2023-01-25    367.959991
2023-01-26    364.869995
2023-01-27    360.769989
2023-01-30    353.109985
2023-01-31    353.859985
Name: Adj Close, dtype: float64
Hand-calculated Monthly Average: 334.75899960000004
monthly average for 2023-1 within combined_monthly: 334.75899960000004